### PR TITLE
Issue #99: NullPointerException with hover and JSON

### LINKED ISSUE #99: NullPointerException with hover and JSON file
Move mouse over false in provided sample:
```json
{
	"aaaa": 		1,
	"bbbb": 		false
}
```
Stacktrace:
```
java.lang.NullPointerException
	at org.eclipse.languageserver.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:44)
	at org.eclipse.ui.internal.genericeditor.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:48)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:166)
```

### PR DESCRIPTION
**Pull request by mniewrzal**
Closes #99

### CODE REVIEW

**Comment by mickaelistria** [comment]
It's a bit tricky to read this code beause of multiple usage of `hover` (not the fault of your patch specifically, it was already before, the patch just make it more visible). Could you please rename the `hover` field to `hoverRequest` or something else that allows to easily distinguish it from actual hover response?

**Comment by mickaelistria** [comment]
I believe it's more the other way round: the field would be the request, whereas the local variable would be the result.

**Comment by mniewrzal** [comment]
Ah, yes. Makes more sense :)

**Comment by mickaelistria** [comment]
Squashed and merged as a8a20b9e2b91709610a6fa063c0397582e6804cf

**Comment by mickaelistria** [comment]
Thanks!

**Pull request closed without merging**
