### PR TITLE
Check ServerCapabilities#getCompletionProvider for completion

### PR DESCRIPTION
**Pull request by angelozerr**
This PR fix problem with CSS completion which starts new launch every time (I don't know why?)

### CODE REVIEW

**Comment by mickaelistria** [comment]
Although the change is good per se, I'm not sure it relates to the issue in title. Please fix title to describe what it changes, and put in comments the side-effect if it's verified.

**Comment by angelozerr** [comment]
@mickaelistria I have updated the title.

**Comment by mickaelistria** [comment]
I was more thinking about the title of the commit (1st line of commit message)

**Comment by angelozerr** [comment]
See my new PR https://github.com/eclipselabs/eclipse-language-service/pull/47

**Pull request closed without merging**
