### PR TITLE
Icons for SymbolKind and CompletionItemKind

### PR DESCRIPTION
**Pull request by mniewrzal**

### CODE REVIEW

**Comment by mniewrzal** [comment]
No all icons are provided, also not all 100% fits for given element but its more about infrastructure. I can also commit svg files.

**Comment by mickaelistria** [comment]
Great!
Icons are usually a bit annoying from IP POV. Can you please clarify where they're coming from? Do you also have some SVG for them?

**Comment by mniewrzal** [comment]
All icons are from 'eclipse.platform.images' (mostly JDT) with some minor changes done by me (just few icons).

**Comment by mickaelistria** [comment]
for variable, what about a "mathematical" `x` like in debug view?
for text, what about an "inked" `xyz` label ?

Ok, I think it's totally fine to reuse Platform images. For the ones you modified, please also include the SVG.

**Comment by mniewrzal** [comment]
> for variable, what about a "mathematical" x like in debug view?
> for text, what about an "inked" xyz label ?

I will prepare something for that + I will add svg files:)

**Comment by mickaelistria** [comment]
I also noticed a function icon in linux tools. Or maybe there is some lambda icon in JDT that would fit as well?

**Comment by mniewrzal** [comment]
Can you show me this function icon from linux tools? I cannot find it. I don't see any special icon for lambda in JDT.

**Comment by mickaelistria** [comment]
Sorry, it wasn't in linuxtools, but in b3: https://github.com/eclipse/b3/blob/master/org.eclipse.b3.beelang.ui/icons/obj16/function.png

**Comment by mniewrzal** [comment]
This is what I can do for now with icons. Next week I want to fill missing icons. In general I would like to see consistent set of icons, right now its mix of icons with different styles ;) But I think its important to improve look and feel of this project :)

**Comment by mickaelistria** [comment]
+1. I'll squash and merge the current set but there is definitely room for improvements later.

**Comment by mickaelistria** [comment]
Squashed and merged as 2983da29835a10bd4df0b3e3c6d1384f97dbf122

**Pull request closed without merging**
