### PR TITLE
Support for 'window/showMessage'

### PR DESCRIPTION
**Pull request by mniewrzal**
Mylyn notifications are used to show messages sent with 'window/showMessage' request.

### CODE REVIEW

**Comment by vladdu** [comment]
Is a dependency on Mylyn acceptable? I think the message handler should be injected via an extension point, so that other providers (or none) can be used.

**Comment by mickaelistria** [comment]
I have no objection against Mylyn, as there is nothing better at the moment in the Eclipse world, and Mylyn notifications have been isolated enough to not require much overhead.
However, do you know the kind of message that's returned? Are Mylyn notification better than pop-ups? Are those notification scoped to a specific file?

**Comment by mniewrzal** [comment]
Mylyn notifications are in EPP packages since Mars so I think overhead will be in most cases none.

> I think the message handler should be injected via an extension point, so that other providers (or none) can be used.

If eclipse-language-service should be extensible then most probably its good idea.

> However, do you know the kind of message that's returned?

Message contains string text and MessageType (info, warning, etc )

> Are Mylyn notification better than pop-ups? 

In case of messages that do not need user interaction I think notifications are better (notifications with timeout would be the best). Popup will block UI until user will close them. 

> Are those notification scoped to a specific file?

No. Messages are global for LS instance. It would be nice to map LS instance with notification to show source of message but I didn't found a way how to do this at the moment.

**Comment by mickaelistria** [comment]
I believe the issue is just that the .target file need to add reference to mylyn notification bundles.

**Comment by bruno-medeiros** [comment]
I also question whether this is a good move, introducing a dependency on Mylyn. Goclipse/RustDT/DDT for example depend only on the Platform(*), and I'd like to keep things that way, even if ELS is used.

(*): well, technically they depend on CDT as well, only because of GDB debugging support.

The thing with Mylyn is that it's not just an dependency invisible to the user, but it affects the UI of the workbench in many ways, and I'd rather my users didn't have to deal with that.

Wasn't there plans to separate the Mylyn notifications to a independent component? I think I remember hearing something about that in the Eclipse mailing lists.

**Comment by kaloyan-raev** [comment]
If I am not wrong, Mylyn Notifications are in isolated Mylyn Commons plugins. So using them does not introduce a dependency to the whole Mylyn project.

**Comment by bruno-medeiros** [comment]
> If I am not wrong, Mylyn Notifications are in isolated Mylyn Commons plugins. So using them does not introduce a dependency to the whole Mylyn project.

Oh, cool then, if that's the case. 👍

**Comment by mickaelistria** [comment]
Added Mylyn to .target than pushed as 9423ace1fc7937c99fa32245374c21b6438f90e1
Thanks!

**Pull request closed without merging**
