### PR TITLE
Support for symbols in workspace

### PR DESCRIPTION
**Pull request by mniewrzal**
This implementation brings dialog to search and open symbol from workspace. Method 'workspace/symbol' is used to query active servers that are attached to given project.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks. This change also seems to contain some refactoring which isn't immediately related to the feature. Do you think you could split this into 2 commits: one with the refactoring and one with the new feature, in order to ease review and make the refactoring visible in history?

**Comment by mniewrzal** [comment]
Sure. No problem :)

**Comment by mickaelistria** [comment]
Could you please also create a separate change for the introduction of the LSPEclipseUtils.openInEditor() method and its usages?

**Comment by mniewrzal** [comment]
> Could you please also create a separate change for the introduction of the LSPEclipseUtils.openInEditor() method and its usages?

Its already merged ;) I will just update this PR.

**Comment by mickaelistria** [comment]
Oh, yeah, it was #79 ;) YEah, updating the PR would be great then.

**Comment by mickaelistria** [comment]
Yet another great patch merged, thanks!

**Pull request merged**
