### PR TITLE
Support open symbols in file

### PR DESCRIPTION
**Pull request by mniewrzal**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thanks, I'd like to merge it soon. Just need to clarify IP things: Rogue Software (as in header) vs Zend (in email), which one would be the copyright owner? It would be easier if email and header were in sync.

**Comment by mickaelistria** [comment]
I also have some ideas about this wizard, such as not automatically following selection (have a checkbox to decide whether editor selection should follow dialog selection), but they can be tracked in future issues/commits.

**Comment by kaloyan-raev** [comment]
@mickaelistria Zend is a Rogue Wave company. Rogue Wave Software acquired Zend Technologies one year ago. Rogue Wave Software is the successor of all Zend IP. Our @zend.com mail accounts are still active and they are still used for our Eclipse.org accounts.

**Comment by mickaelistria** [comment]
Ok, so this pattern is Eclipse-IP-clean, right? If I merge it, it conforms to Eclipse IP rules? You use similar ones in PDT and others?

**Comment by kaloyan-raev** [comment]
I don't see any relationship between IP holder name and the email address' domain name. The email address is a contact info.

Yes, we use similar ones in other contributions to Eclipse.org projects.

**Comment by mickaelistria** [comment]
Ok, thanks @kaloyan-raev  for the info.
Thanks a lot @mniewrzal for this patch, I'll merge it!

**Comment by mickaelistria** [comment]
Merged as fba5f0a83631c9476c357cd31c941c37becdd654

**Pull request closed without merging**
