### PR TITLE
Ctrl+Click (Jump to Definition) should show a hand cursor

### LINKED ISSUE #59: Ctrl+Click (Jump to Definition) should show a hand cursor
When doing Ctrl+Click on some method or value to jump to definition, the cusrsor should be a hand instead of a regular text cursor.

### PR DESCRIPTION
**Pull request by mniewrzal**
Fixes #59

### CODE REVIEW

**Comment by mickaelistria** [comment]
That seems like a good change, although there is no guarantee that a "declarationg" provided by LSP matches a word as you describe it... I'd qualify that as a (valid) workaround caused by a protocol missing data on which range the link applies to.
I'd like to merge it,  but have a few annoying request to make 1st:
- Please edit the copyright header to mention your name as a contributor (that can help for the review when moving code to Eclipse.org)
- Please put some comments to highlight that an ideal world, the Language Server would return which "word" or "area" this applies to, rather than having an arbitrary choice there
- Please report the issue about it to language-server-protocol GitHub repo, to ask for an "appliesTo" value in the response from language server for OpenDefinition.

**Comment by mniewrzal** [comment]
Issue to provide range for definition response is already reported and it looks that isn't added only because lack of time (https://github.com/Microsoft/language-server-protocol/issues/3). 

I will update my patch with copyrights and comments :)

**Comment by mickaelistria** [comment]
Great, thanks!

**Comment by mickaelistria** [comment]
Just a quick IP question before I squash and merge. Copyright header mentions Rogue Wave whereas email address mentions Zend. Is this the scheme you usually use at Eclipse.org?

**Comment by mniewrzal** [comment]
Good point. Zend was acquired by Rogue Wave sometime ago but for now we are using Zend mails. Let me clear this.

**Comment by mickaelistria** [comment]
Merged as c750a9140ffcb72c17482bedab3837ced4105b17 . Thanks a lot!

**Pull request closed without merging**
