### PR TITLE
Issue #96: Add extension point for LS definition

### PR DESCRIPTION
**Pull request by mniewrzal**
This is a draft to start general discussion about final implementation.

### CODE REVIEW

**Comment by mickaelistria** [comment]
PR are currently on hold the yesterday's snapshot was submitted as initial contribution for LSP4E: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12294 . This will be merged in LSP4E as soon as it's ready (I'll be able to take care of rebasing).

**Comment by mickaelistria** [comment]
I like the extension point a lot. Simple and does everything. I'll get to more details a bit later, but overall, I've got a good feeling about this change,

**Comment by mniewrzal** [comment]
Yes, such simple extension point looks to be enough. Maybe just `StreamConnectionProvider` should be extended with `getProcessId()` method.

**Comment by mickaelistria** [comment]
>  Maybe just StreamConnectionProvider should be extended with getProcessId() method.

We need to consider the case of a "remote" language server for which we have no process id and which we connect through WebSockets or other communication protocol. It would be ok to add such methods, but it should be marked as @Nullable then.
Maybe we should discuss it in a separate issue with examples of user-stories.

**Comment by mniewrzal** [comment]
ah I think we misunderstand meaning of `processId`. This is parent process id, in case of LSP4E it should be always Eclipse process id.

https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request

**Comment by mickaelistria** [comment]
Do you think the LSP/content-type associations defined with this extension point are something we'd want to show (in an immutable way) in the Preference Page about Language Servers? If so, we might consider including a "label" attribute.

**Comment by mniewrzal** [comment]
Yes, I think list of 'built-in' servers would be useful. I agree that `label` is a good idea.

**Comment by mniewrzal** [comment]
Except `label` I'm thinking about two additional cases. First one is about adding `id` to reference language server later (e.g. for server preference page definition). Second, how handle many content types for one language server. One way would be to leave it as is and resolve this internally in servers registry, other option is to define LS in extension point and sequence of content types for this language servers.

**Comment by mickaelistria** [comment]
Those are good questions. here are 2 proposals:
1. Have 2 extensions: one for a registry of language server <-> id, and the other allowing to map a content-type<->LS (by id). That would allow to share the same instance of a language server for a given project, whereas the current extension point doesn't allow it
2. Enable multiple content-types for the same LS

1 is probably better, while 2 is probably simpler...

**Comment by mickaelistria** [comment]
Replaced with https://git.eclipse.org/r/#/c/86026/

**Pull request closed without merging**
